### ISSUE TITLE
Show connected wallet info

### ISSUE THREAD

**Issue by edakturk14** [BuidlGuidl/batch2.buidlguidl.com#4]
## Goal

When a user connects to the dApp, let's display 2 things:

1. Is the connected address a member of the batch? (is the in the allowList)
2. Is the connected address already checked in?

Feel free to place that info whenever you want. It could be just some icons that show next to the wallet for members.

For more info about the contract: https://github.com/BuidlGuidl/batch2.buidlguidl.com/issues/9

**Comment by yonathan9669** [comment]
Hello Team, 

What do you think of the following approach, it's simple and explicit I think.

- Transforming the shape of the address avatar from round (anyone) to hexagon (in the allowList). https://daisyui.com/components/avatar/#avatar-with-mask
- If is part of the crew, then a presence (online/offline) indicator could reflect if it's already checked in or not. https://daisyui.com/components/avatar/#avatar-with-presence-indicator

**Comment by carletex** [comment]
Wanna take this one @weslygio ?
