### ISSUE TITLE
Get the check-in count from the Batch Registry contract

### ISSUE THREAD

**Issue by edakturk14** [BuidlGuidl/batch2.buidlguidl.com#5]
## Goal

There is a "To Be implemented" string in `packages/nextjs/app/page.tsx` that should show the number of builders that have checked in to the contract.

We want to show the real count (reading from the BatchRegistry contract)

For more info about the contract: https://github.com/BuidlGuidl/batch2.buidlguidl.com/issues/9

**Comment by carletex** [comment]
Sounds great @weslygio !! Just assigned it to you!

**Comment by carletex** [comment]
Fixed  in #19
