### ISSUE TITLE
Change the Logo / title / subtitle

### ISSUE THREAD

**Issue by edakturk14** [BuidlGuidl/batch2.buidlguidl.com#7]
## Goal

Update your batch's mainpage. 

![284656861-52a77020-0c08-4136-8cc5-244bc3bd088a](https://github.com/BuidlGuidl/batch2.buidlguidl.com/assets/2486142/f9d3495a-9946-4b8e-ac55-8e00cdc380e0)

- Create a random logo (or use Dall-E!) to generate a batch logo
- title: Batch #{batch_number}
- subtitle: Whatever you feel appropriate :)

**Comment by yonathan9669** [comment]
Hello TEAM, I've generated a couple of Logos with Dall-E.

I've explicitly requested to blend ScaffoldEth + BuidlGuidl Logos and to include somehow "Batch #2" and "Building unstoppable apps" in it.

I'll share some of them in a separate message for each so anyone can "vote" and select the one we all like more.

Please, feel free to share your own ideas for the logo and subtitle as mine are just some proposals.

**Comment by yonathan9669** [comment]
![logo](https://github.com/BuidlGuidl/batch2.buidlguidl.com/assets/897389/e6a06199-25b9-4378-b385-5a3aadd2bacf)
![imagen](https://github.com/BuidlGuidl/batch2.buidlguidl.com/assets/897389/c2634f27-4608-4fa0-ad0d-9594e79182d1)
![imagen](https://github.com/BuidlGuidl/batch2.buidlguidl.com/assets/897389/082f31bc-1a3b-44d5-9754-43f54f274de4)
![imagen](https://github.com/BuidlGuidl/batch2.buidlguidl.com/assets/897389/0205375c-7667-4c14-8354-740c4df21e2c)

**Comment by yonathan9669** [comment]
![logo](https://github.com/BuidlGuidl/batch2.buidlguidl.com/assets/897389/9b16c557-524c-490d-b6f0-1a097e7719ea)
![imagen](https://github.com/BuidlGuidl/batch2.buidlguidl.com/assets/897389/ac6ccd4d-5195-4a4d-93ea-5a5754e502de)
![imagen](https://github.com/BuidlGuidl/batch2.buidlguidl.com/assets/897389/56de35c8-2aca-4f2d-9724-5b303adc6aed)
![imagen](https://github.com/BuidlGuidl/batch2.buidlguidl.com/assets/897389/1d26aa8e-6ac0-4645-a8d6-445cdd8866d7)

**Comment by yonathan9669** [comment]
![logo](https://github.com/BuidlGuidl/batch2.buidlguidl.com/assets/897389/ee7af579-9f3e-4c04-8a57-4f11877228dd)
![imagen](https://github.com/BuidlGuidl/batch2.buidlguidl.com/assets/897389/74d4df58-c88f-48e1-8a00-5e24ec1412dd)
![imagen](https://github.com/BuidlGuidl/batch2.buidlguidl.com/assets/897389/88b5abcb-218c-4aa2-85ff-4c94d2f974e8)
![imagen](https://github.com/BuidlGuidl/batch2.buidlguidl.com/assets/897389/91a9c08a-5f13-4221-88fa-9fb48ae4da2c)

**Comment by carletex** [comment]
Want to take this one @smrm-dev ?

**Comment by smrm-dev** [comment]
Of course.
